
const images: {
    [key: string]: number;
}  = {
    
    arrive_left: require('../../../assets/png_navigation_symbol_v2/arrive_left.png'),
    arrive_right: require('../../../assets/png_navigation_symbol_v2/arrive_right.png'),
    arrive_straight: require('../../../assets/png_navigation_symbol_v2/arrive_straight.png'),
    arrive: require('../../../assets/png_navigation_symbol_v2/arrive.png'),
    close: require('../../../assets/png_navigation_symbol_v2/close.png'),
    continue_left: require('../../../assets/png_navigation_symbol_v2/continue_left.png'),
    continue_right: require('../../../assets/png_navigation_symbol_v2/continue_right.png'),
    continue_slight_left: require('../../../assets/png_navigation_symbol_v2/continue_slight_left.png'),
    continue_slight_right: require('../../../assets/png_navigation_symbol_v2/continue_slight_right.png'),
    continue_straight: require('../../../assets/png_navigation_symbol_v2/continue_straight.png'),
    continue_uturn: require('../../../assets/png_navigation_symbol_v2/continue_uturn.png'),
    continue: require('../../../assets/png_navigation_symbol_v2/continue.png'),
    depart_left: require('../../../assets/png_navigation_symbol_v2/depart_left.png'),
    depart_right: require('../../../assets/png_navigation_symbol_v2/depart_right.png'),
    depart_straight: require('../../../assets/png_navigation_symbol_v2/depart_straight.png'),
    depart: require('../../../assets/png_navigation_symbol_v2/depart.png'),
    end_of_road_left: require('../../../assets/png_navigation_symbol_v2/end_of_road_left.png'),
    end_of_road_right: require('../../../assets/png_navigation_symbol_v2/end_of_road_right.png'),
    flag: require('../../../assets/png_navigation_symbol_v2/flag.png'),
    fork_left: require('../../../assets/png_navigation_symbol_v2/fork_left.png'),
    fork_right: require('../../../assets/png_navigation_symbol_v2/fork_right.png'),
    fork_slight_left: require('../../../assets/png_navigation_symbol_v2/fork_slight_left.png'),
    fork_slight_right: require('../../../assets/png_navigation_symbol_v2/fork_slight_right.png'),
    fork_straight: require('../../../assets/png_navigation_symbol_v2/fork_straight.png'),
    fork: require('../../../assets/png_navigation_symbol_v2/fork.png'),
    invalid_left: require('../../../assets/png_navigation_symbol_v2/invalid_left.png'),
    invalid_right: require('../../../assets/png_navigation_symbol_v2/invalid_right.png'),
    invalid_slight_left: require('../../../assets/png_navigation_symbol_v2/invalid_slight_left.png'),
    invalid_slight_right: require('../../../assets/png_navigation_symbol_v2/invalid_slight_right.png'),
    invalid_straight: require('../../../assets/png_navigation_symbol_v2/invalid_straight.png'),
    invalid_uturn: require('../../../assets/png_navigation_symbol_v2/invalid_uturn.png'),
    invalid: require('../../../assets/png_navigation_symbol_v2/invalid.png'),
    merge_left: require('../../../assets/png_navigation_symbol_v2/merge_left.png'),
    merge_right: require('../../../assets/png_navigation_symbol_v2/merge_right.png'),
    merge_slight_left: require('../../../assets/png_navigation_symbol_v2/merge_slight_left.png'),
    merge_slight_right: require('../../../assets/png_navigation_symbol_v2/merge_slight_right.png'),
    merge_straight: require('../../../assets/png_navigation_symbol_v2/merge_straight.png'),
    new_name_left: require('../../../assets/png_navigation_symbol_v2/new_name_left.png'),
    new_name_right: require('../../../assets/png_navigation_symbol_v2/new_name_right.png'),
    new_name_sharp_left: require('../../../assets/png_navigation_symbol_v2/new_name_sharp_left.png'),
    new_name_sharp_right: require('../../../assets/png_navigation_symbol_v2/new_name_sharp_right.png'),
    new_name_slight_left: require('../../../assets/png_navigation_symbol_v2/new_name_slight_left.png'),
    new_name_slight_right: require('../../../assets/png_navigation_symbol_v2/new_name_slight_right.png'),
    new_name_straight: require('../../../assets/png_navigation_symbol_v2/new_name_straight.png'),
    notificaiton_sharp_right: require('../../../assets/png_navigation_symbol_v2/notificaiton_sharp_right.png'),
    notification_left: require('../../../assets/png_navigation_symbol_v2/notification_left.png'),
    notification_right: require('../../../assets/png_navigation_symbol_v2/notification_right.png'),
    notification_sharp_left: require('../../../assets/png_navigation_symbol_v2/notification_sharp_left.png'),
    notification_slight_left: require('../../../assets/png_navigation_symbol_v2/notification_slight_left.png'),
    notification_slight_right: require('../../../assets/png_navigation_symbol_v2/notification_slight_right.png'),
    notification_straight: require('../../../assets/png_navigation_symbol_v2/notification_straight.png'),
    off_ramp_left: require('../../../assets/png_navigation_symbol_v2/off_ramp_left.png'),
    off_ramp_right: require('../../../assets/png_navigation_symbol_v2/off_ramp_right.png'),
    off_ramp_slight_left: require('../../../assets/png_navigation_symbol_v2/off_ramp_slight_left.png'),
    off_ramp_slight_right: require('../../../assets/png_navigation_symbol_v2/off_ramp_slight_right.png'),
    on_ramp_left: require('../../../assets/png_navigation_symbol_v2/on_ramp_left.png'),
    on_ramp_right: require('../../../assets/png_navigation_symbol_v2/on_ramp_right.png'),
    on_ramp_sharp_left: require('../../../assets/png_navigation_symbol_v2/on_ramp_sharp_left.png'),
    on_ramp_sharp_right: require('../../../assets/png_navigation_symbol_v2/on_ramp_sharp_right.png'),
    on_ramp_slight_left: require('../../../assets/png_navigation_symbol_v2/on_ramp_slight_left.png'),
    on_ramp_slight_right: require('../../../assets/png_navigation_symbol_v2/on_ramp_slight_right.png'),
    on_ramp_straight: require('../../../assets/png_navigation_symbol_v2/on_ramp_straight.png'),
    rotary_left: require('../../../assets/png_navigation_symbol_v2/rotary_left.png'),
    rotary_right: require('../../../assets/png_navigation_symbol_v2/rotary_right.png'),
    rotary_sharp_left: require('../../../assets/png_navigation_symbol_v2/rotary_sharp_left.png'),
    rotary_sharp_right: require('../../../assets/png_navigation_symbol_v2/rotary_sharp_right.png'),
    rotary_slight_left: require('../../../assets/png_navigation_symbol_v2/rotary_slight_left.png'),
    rotary_slight_right: require('../../../assets/png_navigation_symbol_v2/rotary_slight_right.png'),
    rotary_straight: require('../../../assets/png_navigation_symbol_v2/rotary_straight.png'),
    rotary: require('../../../assets/png_navigation_symbol_v2/rotary.png'),
    roundabout_left: require('../../../assets/png_navigation_symbol_v2/roundabout_left.png'),
    roundabout_right: require('../../../assets/png_navigation_symbol_v2/roundabout_right.png'),
    roundabout_sharp_left: require('../../../assets/png_navigation_symbol_v2/roundabout_sharp_left.png'),
    roundabout_sharp_right: require('../../../assets/png_navigation_symbol_v2/roundabout_sharp_right.png'),
    roundabout_slight_left: require('../../../assets/png_navigation_symbol_v2/roundabout_slight_left.png'),
    roundabout_slight_right: require('../../../assets/png_navigation_symbol_v2/roundabout_slight_right.png'),
    roundabout_straight: require('../../../assets/png_navigation_symbol_v2/roundabout_straight.png'),
    roundabout: require('../../../assets/png_navigation_symbol_v2/roundabout.png'),
    turn_left: require('../../../assets/png_navigation_symbol_v2/turn_left.png'),
    turn_right: require('../../../assets/png_navigation_symbol_v2/turn_right.png'),
    turn_sharp_left: require('../../../assets/png_navigation_symbol_v2/turn_sharp_left.png'),
    turn_sharp_right: require('../../../assets/png_navigation_symbol_v2/turn_sharp_right.png'),
    turn_slight_left: require('../../../assets/png_navigation_symbol_v2/turn_slight_left.png'),
    turn_slight_right: require('../../../assets/png_navigation_symbol_v2/turn_slight_right.png'),
    turn_straight: require('../../../assets/png_navigation_symbol_v2/turn_straight.png'),
    updown: require('../../../assets/png_navigation_symbol_v2/updown.png'),
    uturn: require('../../../assets/png_navigation_symbol_v2/uturn.png'),
};


export default images;